# default config
params:
  sitemap: true
  debug: false
  cdn: http://localhost:8045
  btnClass: w3-button w3-round w3-hover-lime w3-hover-opacity
  css_load:
    - w3css/5/w3.css
    - css/main.css
    - css/clvq.css
    - chessground/assets/chessground.base.css
    - chessground/assets/chessground.cburnett.css
    - css/chessground.wood4.css
    - css/game.css
  js_load:
    - clvq/main.ts
  sw_js: clvq/sw.js
  screen_ts: game/screen.ts
  game_ts: game/game.ts
  game_loader_js: game/load.js
  game_board_assets:
    - lila/public/images/board/wood4.jpg

menus:
  main:
    - name: Play
      pageref: /play/
      weight: 1
    - name: About
      pageref: /about/
      weight: 9
  game: []
