# default config
params:
  sitemap: true
  debug: false
  cdn: http://localhost:8045
  sw_js: js/service-worker.js
  game_loader_js: js/assets-load.js
  js_load:
    - clvq/main.ts
  game_ts: game/game.ts
  game_setup_ts: game/setup.ts
  game_board_assets:
    - lila/public/images/board/wood4.jpg
  devel_ts: clvq/devel.ts

menus:
  main:
    - name: About
      pageref: /about/
      weight: 1
  game: []
