# default config
params:
  sitemap: true
  debug: false
  cdn: http://localhost:8045
  btnClass: w3-button w3-round-large w3-hover-lime w3-hover-opacity
  modalContentClass: w3-modal-content w3-round-large w3-padding-large w3-black w3-border w3-border-dark-grey
  css_load:
    - css/w3.css
    - css/main.css
    - css/clvq.css
    - chessground/assets/chessground.base.css
    - chessground/assets/chessground.cburnett.css
    - css/chessground.wood4.css
    - css/game.css
    - fontawesome/css/fontawesome.css
    - fontawesome/css/solid.css
  sw_js: js/service-worker.js
  game_loader_js: js/assets-load.js
  js_load:
    - clvq/main.ts
  game_ts: game/game.ts
  game_board_assets:
    - lila/public/images/board/wood4.jpg

menus:
  main:
    - name: About
      pageref: /about/
      weight: 1
  game: []
