baseURL = "http://localhost:8045"
languageCode = "en-us"
title = "Chesslovaquia"
theme = "clvq"

disableKinds = [
	"section",
	"RSS",
	"taxonomy",
]

enableRobotsTXT = true

[caches]
[caches.modules]
dir = ":cacheDir/modules"
maxAge = "15m"
[caches.images]
dir = ":cacheDir/images"

[module]
[[module.mounts]]
source = "js"
target = "assets/js"
[[module.mounts]]
source = "ts/clvq"
target = "assets/clvq"
[[module.mounts]]
source = "ts/game"
target = "assets/game"
[[module.mounts]]
source = "ts/board"
target = "assets/board"
[[module.mounts]]
source = "ts/config"
target = "assets/config"
[[module.mounts]]
source = "ts/events"
target = "assets/events"
[[module.mounts]]
source = "ts/engine"
target = "assets/engine"
[[module.mounts]]
source = "node_modules/chessground"
target = "assets/chessground"
