baseURL = "http://localhost:8045"
languageCode = "en-us"
title = "Chesslovaquia"
theme = "clvq"

disableKinds = [
	"section",
	"RSS",
	"taxonomy",
]

enableRobotsTXT = true

[caches]
[caches.modules]
dir = ":cacheDir/modules"
maxAge = "15m"
[caches.images]
dir = ":cacheDir/images"

[module]
[[module.mounts]]
source = "ts"
target = "assets/js"
[[module.mounts]]
source = "node_modules/chessground"
target = "assets/chessground"
