baseURL = 'http://localhost:8045/'
languageCode = 'en-us'
title = 'chesslovaquia'
theme = 'clvq'

disableKinds = [
	"section",
	"RSS",
	"taxonomy",
]

enableRobotsTXT = true

[caches]
[caches.modules]
dir = ":cacheDir/modules"
maxAge = "15m"

[module]
[[module.mounts]]
source="ts"
target="ts"
