// Copyright (c) Jeremías Casteglione <jrmsdev@gmail.com>
// See LICENSE file.

console.log('This site was generated by Hugo.');

import { w3HideMenu } from './utils';

import { Clvq } from './Clvq';

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
	console.log('Welcome to Chesslovaquia.');
	(window as any).Clvq = new Clvq();
});

window.addEventListener('pageshow', () => {
	w3HideMenu('mobileMenu');
});
