console.log('This site was generated by Hugo.');
console.log('Welcome to Chesslovaquia.');

import { Clvq } from './Clvq';

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
	(window as any).Clvq = new Clvq();
	(window as any).Clvq.init().then(() => {
		console.debug('Clvq init done.');
	});
})
