// Copyright (c) Jeremías Casteglione <jrmsdev@gmail.com>
// See LICENSE file.

import { logger } from './Logger';

import { w3HideMenu } from './utils';

import { Clvq } from './Clvq';

logger.debug('This site was generated by Hugo.');

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
	logger.debug('Welcome to Chesslovaquia.');
	(window as any).Clvq = new Clvq();
});

window.addEventListener('pageshow', () => {
	w3HideMenu('mobileMenu');
});
