console.log('This site was generated by Hugo.');

import { Clvq } from './../clvq/Clvq.js';

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
	(window as any).Clvq = {
		Lib: new Clvq(),
		Game: {},
	}
});
