console.log('This site was generated by Hugo.');

import { Clvq } from './../clvq/Clvq.js';

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
	const clvq = new Clvq();
	// Make instance globally available for debugging
	(window as any).clvq = clvq;
});
