params:
  css_load:
    - css/variables.css
    - css/reset.css
    - css/layout.css
    - css/components.css
    - chessground/assets/chessground.base.css
    - chessground/assets/chessground.cburnett.css
    - css/chessground.wood4.css
    - css/game.css
    - fontawesome/css/fontawesome.css
    - fontawesome/css/solid.css
