name = 'clvq1'
license = 'BSD-3'
licenselink = 'https://github.com/chesslovaquia/LICENSE'
description = 'Chesslovaquia custom theme v1'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/chesslovaquia/chesslovaquia.github.io'

# If you have a running demo of the theme
demosite = 'https://chesslovaquia.github.io/'

# Taxonomy terms
##tags = ['blog', 'company']
##features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Jeremías Casteglione'
  homepage = 'https://github.com/jrmsdev'
