name: check

on:
  push:
    branches:
      - next
  workflow_dispatch:

concurrency:
  group: "checks"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      TZ: UTC
      CLVQ_ROOT: https://chesslovaquia.github.io
      HUGO_PARAMS_CDN: https://equally-capital-python.global.ssl.fastly.net
      HUGO_ENVIRONMENT: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Hugo Install
        run: sudo hugo/install.sh

      - name: Make test
        run: make test
