name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: UTC
      CLVQ_ROOT: https://chesslovaquia.github.io
      HUGO_PARAMS_CDN: https://equally-capital-python.global.ssl.fastly.net
      HUGO_ENVIRONMENT: production

    steps:
      # https://github.com/actions/configure-pages/releases
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # https://github.com/actions/checkout/releases
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Hugo Install
        run: sudo hugo/install.sh

      - name: Install deps
        run: make ci-deps

      - name: Make check
        run: make check

      # https://github.com/actions/upload-pages-artifact/releases
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # https://github.com/actions/deploy-pages/releases
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
